name: Deploy Streamlit to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'streamlit/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_TAG: rentml-streamlit

jobs:
  deploy-streamlit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update Streamlit app on EC2
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=${{ env.EC2_INSTANCE_TAG }}" \
                   "Name=instance-state-name,Values=running" \
          --query "Reservations[0].Instances[0].InstanceId" \
          --output text)
        aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["cd /home/ec2-user/RentML-AWS","git pull"]'

    - name: Install requirements on EC2
      if: contains(github.event.head_commit.modified, 'streamlit/requirements.txt')
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=${{ env.EC2_INSTANCE_TAG }}" \
                   "Name=instance-state-name,Values=running" \
          --query "Reservations[0].Instances[0].InstanceId" \
          --output text)
        aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["cd /home/ec2-user/RentML-AWS/streamlit","pip3 install -r requirements.txt"]'

    - name: Launch Streamlit app on EC2
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=${{ env.EC2_INSTANCE_TAG }}" \
                   "Name=instance-state-name,Values=running" \
          --query "Reservations[0].Instances[0].InstanceId" \
          --output text)
        aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=["pkill -f streamlit","cd /home/ec2-user/RentML-AWS/streamlit","sudo -u ec2-user /usr/local/bin/streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &"]'